version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash -l
  ports:
  - 80
- name: nomad-server
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash -l
  ports:
  - 80
gcp_projects:
- name: nomad
  services:
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - iam.googleapis.com
